showwin/QIDB

app/controllers/home_controller.rb, app/views/home/index.html.erb, app/views/home/output_csv.csv.ruby, config/routes.rb
=> add feature #3

app/controllers/definitions_controller.rb, app/models/definition.rb, app/views/definitions/_edit_form.html.erb, app/views/definitions/edit.html.erb, app/views/definitions/show.html.erb
#2 の機能追加。
但し、複数個入力できる部分のフォームはテーブル表示させないといけないので、後からやる。
=> Add feature #2

app/assets/javascripts/definitions.js, app/controllers/definitions_controller.rb, app/models/definition.rb, app/views/definitions/_edit_form.html.erb, app/views/definitions/_form.html.erb
=> 入力ミス時の自動入力補完

app/controllers/definitions_controller.rb, app/models/change_log.rb, app/models/definition.rb, app/views/definitions/_form.html.erb, app/views/definitions/show.html.erb
=> add_soft_delete

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/definitions.js, app/controllers/application_controller.rb, app/models/definition.rb, app/views/definitions/_edit_form.html.erb
=> CSVデータ変更機能追加

app/controllers/definitions_controller.rb, app/views/definitions/show.html.erb
=> Add feature#27

app/assets/javascripts/definitions.js, app/controllers/definitions_controller.rb, app/controllers/home_controller.rb, app/models/change_log.rb, app/models/definition.rb, app/views/api/v1/definition_api/index.json.jbuilder, app/views/definitions/_edit_form.html.erb, app/views/definitions/show.html.erb, app/views/definitions/success.html.erb, app/views/definitions/upload.html.erb, app/views/home/index.html.erb
=> Refactoring

app/controllers/definitions_controller.rb, config/routes.rb
=> add function (search about qip)

Gemfile, Gemfile.lock, app/controllers/definitions_controller.rb, app/views/definitions/_form.html.erb, app/views/definitions/pdf.pdf.erb, app/views/definitions/show.html.erb, app/views/layouts/pdf.html.erb, config/initializers/wicked_pdf.rb, config/routes.rb
=> Add feature#48

app/models/definition.rb, app/views/definitions/pdf.pdf.erb, app/views/definitions/upload.html.erb
=> Improve #48

Gemfile, Gemfile.lock
#57 に関連して、development環境でより詳細のエラー画面が見られるgem([charliesome/better_errors](https://github.com/charliesome/better_errors))を追加しておきました。
デバッグに便利だと思うので、必要であればmasterにmergeしてください。
=> ADD better_errors gem

.coveralls.yml, .gitignore, Gemfile, Gemfile.lock, README.md, spec/rails_helper.rb
* テストのカバー率を表示する `simplecov` gem の追加
* テストのカバー率を管理する [coverall](https://coveralls.io/github/showwin/QIDB) との連携を追加
=> add simplecov & coverall integration

app/views/home/output_csv.csv.ruby
* CSVのダウンロードをUTF-8からSJISに変更
ref #85, #65
=> change output csv encoding SJIS instead of UTF-8

app/assets/javascripts/definitions.js, app/controllers/application_controller.rb, app/controllers/definitions_controller.rb, app/controllers/home_controller.rb, app/models/definition.rb, app/views/definitions/select.html.erb, app/views/definitions/selected.pdf.erb, app/views/definitions/show.html.erb, app/views/home/index.html.erb, config/routes.rb, spec/features/definition_spec.rb, spec/features/home_spec.rb
=> Add output multi-definition PDF

Capfile, config/deploy.rb, config/deploy/production.rb, scripts/deploy.sh
=> fix capistrano config files

config/deploy/production_circleci.rb, config/unicorn.rb, scripts/deploy.sh
=> Fix CircleCI deploy

app/controllers/definitions_controller.rb, config/initializers/mime_types.rb, config/initializers/wicked_pdf.rb, spec/features/definition_spec.rb
=> download multi-pdfs without login

app/controllers/definitions_controller.rb, config/routes.rb, spec/features/definition_spec.rb
* `/qip/2015/sheet.pdf` でもPDFをダウンロードできるようにする
* テストも追加した
=> download PDF at /:project/:id/sheet.pdf

app/controllers/definitions_controller.rb, app/forms/definition_form.rb, app/views/definitions/_edit_form.html.erb, app/views/definitions/selected.pdf.erb, app/views/definitions/show.pdf.erb, spec/forms/definition_form_spec.rb
* 編集フォームのCSVのファイルアップロードで、アップロードしてもデータが保存されないバグがあったので修正
* PDFのレイアウトで、テーブルが上手く表示されないバグがあったので修正
=> bugfix CSV file upload & bugfix PDF layout

app/controllers/home_controller.rb
CSVダウンロード の year カラムのデータがおかしいのを修正
ref #108
=> fix CSV year column

app/views/home/index.html.erb, spec/features/home_spec.rb
spec/features/home_spec.rb
にテストコードを追加しました。
#115
=> 検索結果の表示内容を変更

.coveralls.yml, spec/rails_helper.rb
#84 で coveralls の CI 連携だけできていなかったので、その修正
=> coveralls の CI 連携

app/controllers/definitions_controller.rb, app/views/definitions/show.html.erb, app/views/definitions/show_table.html.erb, app/views/definitions/show_table_en.html.erb, app/views/home/index.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/definition_spec.rb, spec/features/home_spec.rb, spec/support/create_definition.rb, vendor/assets/stylesheets/sb-admin.css
ref: #112 
検索バー下部のメニューが多すぎて使いづらくなったためデザイン修正した。
=> リスト型の指標表示画面を作成

doc/README.md
APIドキュメントだけ [Wiki](https://github.com/showwin/QIDB/wiki/API-Document) で管理していたので、  `doc/README.md` に移した。
以降、Wiki の API ドキュメントは削除する。
=> APIドキュメントの修正

config/initializers/constants.rb
前回のブランチt132がよくわからなくなってしまったので、改めて最新のmasterからブランチを作成したのですがこれでもよいでしょうか？確認お願いします。
=> add checkbox2016

config/environments/production.rb
=> 動いたのでコメント削除

config/initializers/constants.rb
add 2020 in constants.rb (#180)
=> add 2020 in constants.rb (#180)
